### ISSUE TITLE
Schedule jobs using cron expressions

### ISSUE THREAD

**Issue by jefmathiot** [servebox/electric_sheep#11]
Add support for Cron syntax to help people coming from Cron schedules to make the migration seamlessly:

```ruby
job "I-love-my-job" do
  schedule "cron", expression:  "0 1,7,13,20 * * *"
end
```

See #7.

**Comment by jefmathiot** [comment]
Documentation here http://www.electricsheep.io/v0.5.0/docs/schedule-your-backups#section-cron

**Comment by duckmole** [comment]
Close after review
