### ISSUE TITLE
Support mysql_dump and pg_dump options

### ISSUE THREAD

**Issue by mickaelperrin** [servebox/electric_sheep#22]
Hi,

I would like to use your solution to backup my websites. However, I need to exclude some cache tables of the CMS I use.

Could it be possible to add a setting in the sheepfile to be able to pass some mysqldump or pg_dump parameter (in my case --ignore-table or --exclude-table).

Thanks :)

**Comment by jefmathiot** [comment]
Thanks a lot for reporting, it makes a lot of sense. I don't think we should provide all available options to "keep it stupid simple", but some other could be interesting as well.

* MySQL: `compact`, `flush-log` and locking options. Do you think any other should be included http://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#mysqldump-option-summary ?
* Postgres: as far as I can tell, only the `--no-tablespaces` option could be interesting. http://www.postgresql.org/docs/9.3/static/app-pgdump.html

I wonder if we should make use the same option name for both the commands or stick to the names used by each of the underlying technologies.

```ruby
mysql_dump exclude_tables: ["table1", "table2"]
postgresql_dump exclude_tables: ["table1", "table2"]
# or
mysql_dump ignore_tables: ["table1", "table2"]
postgresql_dump exclude_tables: ["table1", "table2"]
```

Any clue on this @mickaelperrin? + @ehartmann @duckmole

**Comment by duckmole** [comment]
Why did you add `compact` option for MySQL and not `compress` option available in PostgreSQL ?

**Comment by jefmathiot** [comment]
@duckmole makes sense to be able to compress the archive. To do so, one has to use the `-F` flag to change the output format to "custom" which is compressed by default and can be used as-is by `pg_restore` : `pg_dump -Fp db > db.sql`.

The `--compress` option is used to fine tune the level of compression. High values of compression make the dump process slower. I think we should use the default compression level to keep the command simple to use.

**Comment by mickaelperrin** [comment]
I was just wondering, why not just add an "option / params" parameter that allows sys admin to use their favrourite script syntax in the sheep file without having to learn a new way to write these options in a sheep file.

Doing so, can handle all particular use cases without having to manage all specific parameters of mysql_dump, pg_dump and others DB_dump.

This sounds much simpler to implement, and to migrate backup scripts, at the price of maybe a less "rubyish" code style.
