### ISSUE TITLE
SSH PORT

### ISSUE THREAD

**Issue by tboulogne** [servebox/electric_sheep#23]
Hello,

Could you complete the documentation on the part regarding default values and add the ssh_port option please ? It could help others... i found it looking into code :-).

> host "my-app-host", hostname: "host.example.com", ssh_port: 22222

Thanks for all :-).

**Comment by duckmole** [comment]
Thk, for this useful remark
I updated the documentation with your remark : [Configuring remote access](http://www.electricsheep.io/v0.5.0/docs/getting-started#section-configuring-remote-access)

We have to add a page on documentation, to list all the options for `host`
