### ISSUE TITLE
AMD 64 package does not work on Debian 7

### ISSUE THREAD

**Issue by SlyZeSpy** [servebox/electric_sheep#3]
I tried installing the ElectricSheeIO AMD 64 on Debian 7 and i get an error message when trying to launch : 

```
~# electric_sheep
/opt/electric_sheep/embedded/bin/ruby: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /opt/electric_sheep/embedded/lib/libruby.so.1.9)
```

Previous steps are conducted properly

**Comment by duckmole** [comment]
The version 0.2.1 fix this issue.
http://electricsheepio.readme.io/v0.2.1/page/downloads
