### ISSUE TITLE
Exclusion in a job

### ISSUE THREAD

**Issue by SlyZeSpy** [servebox/electric_sheep#6]
I need to make an exclusion in a backup job to avoid a directory containing large static files (e.g. video) to be included.
Have you planned this case?

**Comment by jefmathiot** [comment]
You mean when compressing a directory with `tar_gz` ? There's no solution available at the time of speaking, but your request makes sense.

**Comment by SlyZeSpy** [comment]
That's right !
Thanks for your reply.

**Comment by mickaelperrin** [comment]
+1

And thanks for your talk at /dev/var ;)

**Comment by jefmathiot** [comment]
@SlyZeSpy @mickaelperrin I'll include this enhancement in the next release (end of december).

**Comment by jefmathiot** [comment]
Documented here http://www.electricsheep.io/v0.6.0/docs/compression
